// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kotkjuhregqhczxhsynd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtvdGtqdWhyZWdxaGN6eGhzeW5kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5OTc3NTksImV4cCI6MjA3MDU3Mzc1OX0.l59FmUako3en5ZmQTMBW3X25AoU5ktiUodOYuLW3qok";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});